#!/bin/bash

# E-Commerce Application - Quick Start Guide
# This script displays instructions to run all three applications

echo "================================================"
echo "  E-Commerce Full Stack Application"
echo "  Quick Start Guide"
echo "================================================"
echo ""
echo "⚠️  BEFORE RUNNING: Setup Environment Variables"
echo ""
echo "   Backend (macOS/Linux): cp backend/.env.example backend/.env"
echo "   Backend (Windows):     copy backend\\.env.example backend\\.env"
echo ""
echo "   Frontend (macOS/Linux): cp frontend/.env.example frontend/.env.local"
echo "   Frontend (Windows):     copy frontend\\.env.example frontend\\.env.local"
echo ""
echo "   Then edit the .env files with your actual values!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To run the full application, you need to start 3 services:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  BACKEND (Python/Flask) - Port 5000"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   macOS/Linux:"
echo "   cd backend"
echo "   source .venv/bin/activate"
echo "   python3 app.py"
echo ""
echo "   Windows:"
echo "   cd backend"
echo "   .venv\\Scripts\\activate"
echo "   python app.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  FRONTEND (Next.js) - Port 3000"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   macOS/Linux/Windows:"
echo "   cd frontend"
echo "   npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  MODEL3D (Vite/React) - Port 5173"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   macOS/Linux/Windows:"
echo "   cd model3d"
echo "   npm run dev"
echo ""
echo "================================================"
echo "  Access Your Applications:"
echo "================================================"
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:5000"
echo "  Admin:     http://localhost:5000/admin"
echo "  Model3D:   http://localhost:5173"
echo ""
echo "💡 Tip: Open 3 terminal tabs in VS Code and run each command above"
echo "📖 Full documentation: See START.md for detailed instructions"
echo ""

